### ISSUE TITLE
Does not upload 0 byte files or filenames with % and & characters

### ISSUE THREAD

**Issue by SpiralGalaxy** [Rambalac/AmazonCloudDriveApi#9] opened 2016-04-13 03:11 UTC
Window 7 x64
It pretends to upload zero byte files but they never actually get uploaded.

Files with & in the name fail with the following error.

![copy file](https://cloud.githubusercontent.com/assets/10256450/14481738/ed5d06cc-0103-11e6-8800-60c63586383d.png)

There might be other characters that present problems.

**Comment by Rambalac** [comment] 2016-04-14 02:34
Yes. Amazon Cloud Drive does not allow empty files. I have one idea but it's a bit ugly.

Funny. & worked, I tested it before. And API unittest has no problem with &

**Comment by SpiralGalaxy** [comment] 2016-04-14 02:56
Zero byte files upload fine either through the web interface of their official app so they do allow them....

![0 byte file via app](https://cloud.githubusercontent.com/assets/10256450/14515765/f74dc4e2-01ca-11e6-918c-c3bd29f22c16.png)

![0 byte file via site](https://cloud.githubusercontent.com/assets/10256450/14515766/f74eb866-01ca-11e6-8f13-609dcf3c054f.png)

**Comment by Rambalac** [comment] 2016-04-14 03:53
Ok, I will check zero files. Half year ago I had to make workaround for zero size.

**Comment by Rambalac** [comment] 2016-04-14 05:07
No, nothing changed. The only opened REST API does not allow to upload zero length files.
It's >>> By design
https://forums.developer.amazon.com/forums/thread.jspa?messageID=22525&#22525

**Comment by Rambalac** [comment] 2016-04-14 08:07
I updated ACDDokanNet project and published new release 1.5.5.
Please test it and confirm if it's working. It does not have any zero length files hack so files will be ignored for now.

**Comment by SpiralGalaxy** [comment] 2016-04-14 09:51
Thanks but I don't see the installer for 1.5.5.

**Comment by Rambalac** [comment] 2016-04-14 10:04
This project is .NET library and released in Nuget. If you need Windows disk drive it's in https://github.com/Rambalac/ACDDokanNet

**Comment by SpiralGalaxy** [comment] 2016-04-14 10:33
Sorry I don't know what all that means. For all previous version I just downloaded the file named ACDDokanNetInstaller.msi, double clicked it and it installed the program. For version 1.5.5, ACDDokanNetInstaller.msi is not there.

Older version...
https://github.com/Rambalac/ACDDokanNet/releases/

**Comment by Rambalac** [comment] 2016-04-14 11:43
Ah, yeah, sorry, my bad, forgot to click upload button. Done

**Comment by SpiralGalaxy** [comment] 2016-04-14 11:55
Filenames with those symbols upload fine now.
Thanks

**Comment by Rambalac** [comment] 2016-04-14 11:57
I will create separate issue for zero length files

**Closed** 2016-04-14 11:56 UTC
